/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArmyAnt_Java_AANeuron 
	Java 类 ArmyAnt.Java_AANeuron的C头文件
*/

#ifndef _Included_ArmyAnt_Java_AANeuron_2016_2_24
#define _Included_ArmyAnt_Java_AANeuron_2016_2_24
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Liner
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Liner
  (JNIEnv *, jclass, jdouble input, jdouble slope, jdouble bias);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Ramp
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Ramp
  (JNIEnv *, jclass, jdouble input, jdouble width, jdouble height);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Threshold
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Threshold
  (JNIEnv *, jclass, jdouble input, jdouble amplitude, jdouble threshold);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Sigmoid
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Sigmoid
  (JNIEnv *, jclass, jdouble input, jdouble coef);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    DoubleSigmoid
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_DoubleSigmoid
  (JNIEnv *, jclass, jdouble input, jdouble coef);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_Create
 * Signature: (LArmyAnt/Java_AANeuron/INeuronActive;D)J
 */
JNIEXPORT jlong JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1Create
  (JNIEnv *, jclass, jobject funcInterface, jdouble threshold);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_Clone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1Clone
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_Release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1Release
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_JoinActive
 * Signature: (JDD)Z
 */
JNIEXPORT jboolean JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1JoinActive
  (JNIEnv *, jclass, jlong value, jdouble input, jdouble weight);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_LeaveActive
 * Signature: (JDD)Z
 */
JNIEXPORT jboolean JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1LeaveActive
  (JNIEnv *, jclass, jlong value, jdouble input, jdouble weight);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_ClearActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1ClearActive
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_GetOutput
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1GetOutput
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_GetAllActive
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1GetAllActive
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_SetActiveInterface
 * Signature: (JLArmyAnt/Java_AANeuron/INeuronActive;)Z
 */
JNIEXPORT jboolean JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1SetActiveInterface
  (JNIEnv *, jclass, jlong value, jobject funcInterface);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_GetThreshold
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1GetThreshold
  (JNIEnv *, jclass, jlong value);

/*
 * Class:     ArmyAnt_Java_AANeuron
 * Method:    Native_SetThreshold
 * Signature: (JD)Z
 */
JNIEXPORT jboolean JNICALL Java_ArmyAnt_Java_1AANeuron_Native_1SetThreshold
  (JNIEnv *, jclass, jlong value, jdouble threshold);

#ifdef __cplusplus
}
#endif

#endif // _Included_ArmyAnt_Java_AANeuron_2016_2_24
